"use strict";
const crypto=require("node:crypto");
const {canonicalize,hashCanonical}=require("../generation/canonical.cjs");
const {FRANKEN_SCHEMA,FRANKEN_POLICY,FPS,DURATION_FRAMES}=require("./schema.cjs");
const {normalizeEdits}=require("./proposal.cjs");
const SCENE_SPANS={ARRIVE:[0,384],CROSS:[384,384],ASSEMBLE:[768,384]};
function digestText(text){return crypto.createHash("sha256").update(String(text),"utf8").digest("hex");}
function unit(seed,key){const h=crypto.createHash("sha256").update(`${seed}|${key}`).digest();return h.readUInt32BE(0)/0xffffffff;}
function cleanCardMaterial(card){return {materialId:card.materialId,kind:"image",sourceIdentity:`playdeck:${card.source}`,digest:card.digest,rightsBasis:"repository-owned-or-explicitly-admitted",admissionBasis:"playdeck-proposal"};}
function cleanVideoMaterial(blender){const m=blender.material;return {materialId:m.materialId,kind:"video",sourceIdentity:m.sourceIdentity,digest:m.digest,rightsBasis:m.rightsBasis,admissionBasis:m.admissionBasis};}
function stateFromDonors({playdeck,blenderTake,seed}){
 if(playdeck?.authority!=="proposal-only"||blenderTake?.authority!=="material-only")throw new TypeError("Franken composer requires bounded Playdeck and Blender donor adapters.");
 if(typeof seed!=="string"||!seed.trim())throw new TypeError("Franken seed is required.");
 const cardIds=playdeck.cards.map(c=>c.cardId);
 return {seed:seed.trim(),cardOrder:cardIds,sceneRoles:Object.fromEntries(cardIds.map((id,i)=>[id,["ARRIVE","CROSS","ASSEMBLE"][Math.floor(i/2)]])),worldRule:playdeck.worldRule.id,movingTakeSceneId:"CROSS",transitions:{arriveCross:"panel-wipe",crossAssemble:"radial-reveal"},text:"THE ROOM REMEMBERS",variation:0};
}
function buildProposal(playdeck,blenderTake,state){
 const cardsById=new Map(playdeck.cards.map(c=>[c.cardId,c]));
 if(state.cardOrder.some(id=>!cardsById.has(id)))throw new TypeError("cardOrder references an unknown Playdeck card.");
 const textDigest=digestText(state.text);
 const topologyIdentity=canonicalize({kind:"manga-impact-topology",seed:state.seed,variation:state.variation,worldRule:state.worldRule});
 const topologyDigest=hashCanonical(topologyIdentity,"HauntedToaster-FrankenTopology-v0");
 const materials=[...state.cardOrder.map(id=>cleanCardMaterial(cardsById.get(id))),cleanVideoMaterial(blenderTake),{materialId:"franken:text",kind:"text",sourceIdentity:`text:${textDigest}:${state.text}`,digest:textDigest,rightsBasis:"human-authored-inline",admissionBasis:"explicit-editor-text"},{materialId:"franken:topology",kind:"generated-shape",sourceIdentity:`generated:${topologyDigest}`,digest:topologyDigest,rightsBasis:"deterministic-local-generation",admissionBasis:"franken-topology-v0"}];
 const scenes=Object.entries(SCENE_SPANS).map(([sceneId,[startFrame,durationFrames]])=>{
   const assigned=state.cardOrder.filter(id=>state.sceneRoles[id]===sceneId);
   const tracks=assigned.map((id,i)=>{const card=cardsById.get(id);const u=unit(`${state.seed}:${state.variation}`,`${sceneId}:${id}`);const v=unit(`${state.seed}:${state.variation}`,`${sceneId}:${id}:y`);return {trackId:`${sceneId.toLowerCase()}-${id}`,layer:`card-${i}`,role:"card",clips:[{clipId:`clip-${sceneId.toLowerCase()}-${id}`,materialId:card.materialId,startFrame,durationFrames,sourceWindow:null,transform:{x:0.3+u*0.4,y:0.35+v*0.3,scale:0.82+u*0.22,rotationDegrees:Math.round((u-0.5)*12)},crop:card.crop??null,opacity:1,blend:"normal",entrance:sceneId==="ARRIVE"?"arrive":"hinge",transitionRelation:null}]};});
   if(sceneId===state.movingTakeSceneId){const m=blenderTake.material;tracks.push({trackId:`${sceneId.toLowerCase()}-moving-take`,layer:"moving-take",role:"moving-take",clips:[{clipId:`clip-${sceneId.toLowerCase()}-moving-take`,materialId:m.materialId,startFrame:startFrame+96,durationFrames:72,sourceWindow:{startSeconds:0,endSeconds:3},transform:{x:0.5,y:0.5,scale:0.72,rotationDegrees:0},crop:null,opacity:1,blend:"normal",entrance:"portal",transitionRelation:null}]});}
   tracks.push({trackId:`${sceneId.toLowerCase()}-type`,layer:"type",role:"typography",clips:[{clipId:`clip-${sceneId.toLowerCase()}-type`,materialId:"franken:text",startFrame:startFrame+48,durationFrames:192,sourceWindow:null,transform:{x:0.5,y:0.82,scale:1,rotationDegrees:sceneId==="CROSS"?-3:0},crop:null,opacity:0.92,blend:"normal",entrance:"speak",transitionRelation:null}]});
   if(sceneId!=="ARRIVE")tracks.push({trackId:`${sceneId.toLowerCase()}-topology`,layer:"background",role:"topology-material",clips:[{clipId:`clip-${sceneId.toLowerCase()}-topology`,materialId:"franken:topology",startFrame,durationFrames,sourceWindow:null,transform:{x:0.5,y:0.5,scale:1,rotationDegrees:state.variation%4*90},crop:null,opacity:0.55,blend:"screen",entrance:"grow",transitionRelation:null}]});
   return {sceneId,startFrame,durationFrames,worldRule:state.worldRule,tracks};
 });
 const donorGuards={playdeckSnapshot:playdeck.ancestry.snapshotHash,blenderVideo:blenderTake.material.digest,blenderReceipt:blenderTake.ancestry.admissionReceiptSha256};
 const ancestry={toasterCarrier:"experimental/hyperkitchen-001-hyperframes-projection",toasterCandidateOrPlan:"franken-proposal-only",playdeckSnapshot:donorGuards.playdeckSnapshot,blenderTakeAcceptance:donorGuards.blenderReceipt};
 return canonicalize({proposalSchema:"static-collective/franken-proposal/v0",authority:"proposal-only",seed:state.seed,cardOrder:state.cardOrder,sceneRoles:state.sceneRoles,worldRule:state.worldRule,movingTakeSceneId:state.movingTakeSceneId,transitionChoices:state.transitions,text:state.text,variation:state.variation,donorGuards,ancestry,materials,scenes,transitions:[{transitionId:"arrive-cross",fromSceneId:"ARRIVE",toSceneId:"CROSS",kind:state.transitions.arriveCross,durationFrames:state.transitions.arriveCross==="cut"?1:18,parameters:{}},{transitionId:"cross-assemble",fromSceneId:"CROSS",toSceneId:"ASSEMBLE",kind:state.transitions.crossAssemble,durationFrames:state.transitions.crossAssemble==="cut"?1:24,parameters:{}}],_donor:{playdeck,blenderTake}});
}
function composeFrankenProposal({playdeck,blenderTake,seed}={}){return buildProposal(playdeck,blenderTake,stateFromDonors({playdeck,blenderTake,seed}));}
function applyFrankenEdits(proposal,edits={}){if(proposal?.proposalSchema!=="static-collective/franken-proposal/v0")throw new TypeError("Expected a Franken proposal.");const state=normalizeEdits({seed:proposal.seed,cardOrder:proposal.cardOrder,sceneRoles:proposal.sceneRoles,worldRule:proposal.worldRule,movingTakeSceneId:proposal.movingTakeSceneId,transitions:proposal.transitionChoices,text:proposal.text,variation:proposal.variation},edits);return buildProposal(proposal._donor.playdeck,proposal._donor.blenderTake,state);}
function proposalToComposition(proposal){if(proposal?.proposalSchema!=="static-collective/franken-proposal/v0")throw new TypeError("Expected a Franken proposal.");if(proposal.ancestry.playdeckSnapshot!==proposal.donorGuards.playdeckSnapshot||proposal.ancestry.blenderTakeAcceptance!==proposal.donorGuards.blenderReceipt||proposal._donor.playdeck.ancestry.snapshotHash!==proposal.donorGuards.playdeckSnapshot||proposal._donor.blenderTake.material.digest!==proposal.donorGuards.blenderVideo||proposal._donor.blenderTake.ancestry.admissionReceiptSha256!==proposal.donorGuards.blenderReceipt)throw new TypeError("Stale donor identity detected before freeze.");return {schema:FRANKEN_SCHEMA,policy:FRANKEN_POLICY,compositionId:`fc0_${hashCanonical({seed:proposal.seed,variation:proposal.variation,cardOrder:proposal.cardOrder,sceneRoles:proposal.sceneRoles,transitionChoices:proposal.transitionChoices,text:proposal.text},"HauntedToaster-FrankenProposal-v0")}`,seed:`${proposal.seed}:${proposal.variation}`,fps:FPS,durationFrames:DURATION_FRAMES,ancestry:proposal.ancestry,materials:proposal.materials,scenes:proposal.scenes,transitions:proposal.transitions,receipts:{policyVersion:FRANKEN_POLICY}};}
module.exports={composeFrankenProposal,applyFrankenEdits,proposalToComposition};
