const test = require('node:test');
const assert = require('node:assert/strict');
const {freezeFrankenComposition} = require('../src/franken-composer/freeze.cjs');
const {semanticTrace} = require('../src/franken-composer/trace.cjs');
function fixture(){return {schema:'static-collective/franken-composition/v0',policy:'franken-composer/v0',compositionId:'fc-test',seed:'seed-a',fps:24,durationFrames:1152,ancestry:{toasterCarrier:'abc',toasterCandidateOrPlan:'cand',playdeckSnapshot:'deck',blenderTakeAcceptance:'take'},materials:[{materialId:'m1',kind:'image',sourceIdentity:'s1',digest:'a'.repeat(64),rightsBasis:'fixture',admissionBasis:'test'},{materialId:'v1',kind:'video',sourceIdentity:'v',digest:'b'.repeat(64),rightsBasis:'fixture',admissionBasis:'filmmaker_accepted_private_preview'}],scenes:[{sceneId:'ARRIVE',startFrame:0,durationFrames:384,worldRule:'comic-page',tracks:[{trackId:'t1',layer:'mid',role:'card',clips:[{clipId:'c1',materialId:'m1',startFrame:0,durationFrames:384,sourceWindow:null,transform:{x:0.5,y:0.5,scale:1,rotationDegrees:0},crop:null,opacity:1,blend:'normal',entrance:'arrive',transitionRelation:null}]}]},{sceneId:'CROSS',startFrame:384,durationFrames:384,worldRule:'manga',tracks:[{trackId:'t2',layer:'mid',role:'moving-take',clips:[{clipId:'c2',materialId:'v1',startFrame:384,durationFrames:120,sourceWindow:{startSeconds:0,endSeconds:5},transform:{x:0.5,y:0.5,scale:1,rotationDegrees:0},crop:null,opacity:1,blend:'normal',entrance:'portal',transitionRelation:null}]}]},{sceneId:'ASSEMBLE',startFrame:768,durationFrames:384,worldRule:'room',tracks:[]}],transitions:[{transitionId:'tr1',fromSceneId:'ARRIVE',toSceneId:'CROSS',kind:'panel-wipe',durationFrames:18,parameters:{}},{transitionId:'tr2',fromSceneId:'CROSS',toSceneId:'ASSEMBLE',kind:'radial-reveal',durationFrames:24,parameters:{}}],receipts:{policyVersion:'franken-composer/v0'}};}
test('same inputs produce byte-identical frozen plan and hash',()=>{const a=freezeFrankenComposition(fixture()),b=freezeFrankenComposition(fixture());assert.deepEqual(a.bytes,b.bytes);assert.equal(a.planHash,b.planHash);assert.equal(a.plan.schema,'static-collective/franken-composition/v0');assert.equal(a.plan.fps,24);assert.equal(a.plan.durationFrames,1152);});
test('explicit semantic delta changes canonical plan hash',()=>{const a=freezeFrankenComposition(fixture());const f=fixture();f.scenes[0].tracks[0].clips[0].opacity=.5;const b=freezeFrankenComposition(f);assert.notEqual(a.planHash,b.planHash);});
test('invalid scene spans transition references and excessive track overlap refuse',()=>{const f=fixture();f.scenes[0].durationFrames=0;assert.throws(()=>freezeFrankenComposition(f),/scene span/i);const g=fixture();g.transitions[0].toSceneId='MISSING';assert.throws(()=>freezeFrankenComposition(g),/transition/i);const h=fixture();const base=h.scenes[0].tracks[0].clips[0];h.scenes[0].tracks=[0,1,2].map(i=>({trackId:'x'+i,layer:'mid',role:'card',clips:[{...base,clipId:'cx'+i}]}));assert.throws(()=>freezeFrankenComposition(h),/overlap/i);});
test('canonical plan is deeply frozen and cannot be mutated after hashing',()=>{const {plan}=freezeFrankenComposition(fixture());assert.ok(Object.isFrozen(plan));assert.ok(Object.isFrozen(plan.scenes));assert.ok(Object.isFrozen(plan.scenes[0].tracks[0].clips[0]));});
test('semantic trace strips renderer-local fields but preserves required parity fields',()=>{const {plan}=freezeFrankenComposition(fixture());plan.rendererLocal='ignored';const t=semanticTrace(plan);assert.equal(t.fps,24);assert.equal(t.scenes[1].tracks[0].clips[0].materialId,'v1');assert.equal(t.transitions[1].kind,'radial-reveal');assert.equal(t.rendererLocal,undefined);});
