"use strict";
const {canonicalize,hashCanonical,deepFreeze}=require("../../generation/canonical.cjs");
const {semanticTrace}=require("../trace.cjs");
const ALLOWED_TRANSITIONS=new Set(["panel-wipe","radial-reveal","cut","hinge"]);
const ALLOWED_BLENDS=new Set(["normal","screen"]);
function esc(v){return String(v).replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/</g,"&lt;").replace(/>/g,"&gt;");}
function assertSupported(plan){for(const t of plan.transitions){if(!ALLOWED_TRANSITIONS.has(t.kind))throw new TypeError(`Unsupported transition for HyperFrames: ${t.kind}.`);}for(const s of plan.scenes)for(const track of s.tracks)for(const clip of track.clips){if(!ALLOWED_BLENDS.has(clip.blend))throw new TypeError(`Unsupported blend for HyperFrames: ${clip.blend}.`);for(const key of ["x","y","scale","rotationDegrees"]){if(!Number.isFinite(clip.transform?.[key]))throw new TypeError(`Unsupported transform for HyperFrames: ${key}.`);}}}
function assertPlanHash(plan,planHash){const clone=canonicalize(plan);if(clone.receipts)delete clone.receipts.planHash;const observed=hashCanonical(clone,"HauntedToaster-FrankenComposition-v0");if(observed!==planHash||plan.receipts?.planHash!==planHash)throw new TypeError("HyperFrames projection refuses a mutated or mismatched frozen plan.");}
function materialHtml(material,binding){if(material.kind==="image"||material.kind==="video"){if(typeof binding!=="string"||!binding)throw new TypeError(`Missing asset binding for ${material.materialId}.`);const tag=material.kind==="video"?"video":"img";return `<${tag} src="${esc(binding)}" ${tag==="video"?'muted playsinline':''}></${tag}>`;}if(material.kind==="text"){const parts=material.sourceIdentity.split(":");return `<span class="franken-text">${esc(parts.slice(2).join(":"))}</span>`;}return '<span class="franken-topology" aria-hidden="true"></span>';}
function compileHyperFramesFranken({plan,planHash,assetBindings={}}={}){
 if(!plan||typeof plan!=="object")throw new TypeError("HyperFrames projector requires a frozen Franken plan.");
 assertSupported(plan);assertPlanHash(plan,planHash);
 const materials=new Map(plan.materials.map(m=>[m.materialId,m]));let trackIndex=0;const nodes=[];const timeline=[];
 for(const scene of plan.scenes){for(const track of scene.tracks){for(const clip of track.clips){const material=materials.get(clip.materialId);if(!material)throw new TypeError(`Missing material ${clip.materialId}.`);const start=clip.startFrame/plan.fps,duration=clip.durationFrames/plan.fps;const id=`hf-${clip.clipId}`;const style=`left:${clip.transform.x*100}%;top:${clip.transform.y*100}%;transform:translate(-50%,-50%) scale(${clip.transform.scale}) rotate(${clip.transform.rotationDegrees}deg);opacity:${clip.opacity};mix-blend-mode:${clip.blend};`;nodes.push(`<div id="${esc(id)}" class="franken-clip role-${esc(track.role)}" data-clip-id="${esc(clip.clipId)}" data-start="${start}" data-duration="${duration}" data-track-index="${trackIndex}" data-entrance="${esc(clip.entrance)}" style="${style}">${materialHtml(material,assetBindings[material.materialId])}</div>`);timeline.push({id,start,duration,entrance:clip.entrance});trackIndex++;}}}
 const compositionId=`hf-franken-${planHash.slice(0,12)}`;const seconds=plan.durationFrames/plan.fps;const timelineJson=JSON.stringify(timeline).replace(/</g,"\\u003c");const html=`<!doctype html><html><head><meta charset="utf-8"><style>html,body{margin:0;background:#0b0b10;overflow:hidden}.stage{position:relative;width:1280px;height:720px;overflow:hidden}.franken-clip{position:absolute;transform-origin:center}.franken-clip img,.franken-clip video{display:block;max-width:720px;max-height:640px}.franken-text{font:900 64px/1 sans-serif;color:white;text-shadow:4px 4px 0 #000}.franken-topology{display:block;width:900px;height:900px;border:28px double white;border-radius:50%;filter:contrast(1.4)}</style></head><body><main class="stage" data-composition-id="${compositionId}" data-total-duration="${seconds}">${nodes.join("")}</main><script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js"></script><script>window.__timelines=window.__timelines||{};const clips=${timelineJson};const tl=gsap.timeline({paused:true});for(const c of clips){tl.fromTo('#'+c.id,{opacity:0,scale:0.92},{opacity:1,scale:1,duration:Math.min(.35,c.duration),ease:'none'},c.start);}window.__timelines['${compositionId}']=tl;</script></body></html>`;
 const trace=semanticTrace(plan);const manifest=deepFreeze(canonicalize({schema:"static-collective/franken-hyperframes-projection/v0",projectionId:compositionId,planHash,fps:plan.fps,durationFrames:plan.durationFrames,transitions:plan.transitions.map(t=>({transitionId:t.transitionId,kind:t.kind,durationFrames:t.durationFrames})),hiddenExitSemantics:false,trackCount:trackIndex,authority:"projection-only"}));
 return deepFreeze({manifest,html,semanticTrace:trace,projectionHash:hashCanonical({manifest,html},"HauntedToaster-FrankenHyperFrames-v0")});
}
module.exports={compileHyperFramesFranken};
