"use strict";
const {canonicalize,hashCanonical,deepFreeze}=require("../../generation/canonical.cjs");
const {semanticTrace}=require("../trace.cjs");
const ALLOWED_TRANSITIONS=new Set(["panel-wipe","radial-reveal"]);
const ALLOWED_BLENDS=new Set(["normal","screen"]);
const DESIGN_MD=`# Franken Composer HyperFrames — Visual Identity\n\n## Style Prompt\nHigh-contrast deterministic manga collage: cheap-newsprint physicality, addressable cutout panels, hard ink boundaries, halftone pressure, witness-gold transition cards, and one bounded moving portal. The image should feel assembled by a director/editor rather than generated as a continuous dream.\n\n## Colors\n- Canvas: #0B0B10\n- Paper white: #F5F1E8\n- Ink red: #D94B4B\n- Witness gold: #F4DF9C\n- Shadow violet: #17131F\n\n## Typography\n- Display: system sans-serif, heavy display weight\n- Technical/witness labels: IBM Plex Mono, 350-500\n\n## What NOT to Do\n- No generic blue SaaS gradients.\n- No ambient particle wallpaper or spectrum bars.\n- No hidden generative interpolation between accepted scenes.\n- No exit animations before scene transitions.\n- No tiny web-scale typography.\n`;
function esc(v){return String(v).replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/</g,"&lt;").replace(/>/g,"&gt;");}
function assertSupported(plan){for(const t of plan.transitions){if(!ALLOWED_TRANSITIONS.has(t.kind))throw new TypeError(`Unsupported transition for HyperFrames: ${t.kind}.`);}const byMaterial=new Map(plan.materials.map(m=>[m.materialId,m]));for(const s of plan.scenes)for(const track of s.tracks)for(const clip of track.clips){if(!ALLOWED_BLENDS.has(clip.blend))throw new TypeError(`Unsupported blend for HyperFrames: ${clip.blend}.`);for(const key of ["x","y","scale","rotationDegrees"]){if(!Number.isFinite(clip.transform?.[key]))throw new TypeError(`Unsupported transform for HyperFrames: ${key}.`);}const material=byMaterial.get(clip.materialId);if(material?.kind==="video"&&clip.crop)throw new TypeError("HyperFrames founding projector refuses video crop; shared renderer parity only admits image crop in v0.");if(material?.kind==="video"&&clip.sourceWindow){const sourceFrames=Math.round((clip.sourceWindow.endSeconds-clip.sourceWindow.startSeconds)*plan.fps);if(clip.sourceWindow.startSeconds!==0||clip.durationFrames>sourceFrames)throw new TypeError("HyperFrames founding video projector only supports a zero-based source window that covers the full clip duration.");}}}
function assertPlanHash(plan,planHash){const clone=canonicalize(plan);if(clone.receipts)delete clone.receipts.planHash;const observed=hashCanonical(clone,"HauntedToaster-FrankenComposition-v0");if(observed!==planHash||plan.receipts?.planHash!==planHash)throw new TypeError("HyperFrames projection refuses a mutated or mismatched frozen plan.");}
function cropMediaStyle(crop){return `position:absolute;width:${100/crop.width}%;height:${100/crop.height}%;left:${-(crop.x/crop.width)*100}%;top:${-(crop.y/crop.height)*100}%;max-width:none;max-height:none;`;}
function materialNode(material,binding,attrs,style,crop,role){const roleClass=`role-${esc(role)}`;if(material.kind==="image"){if(typeof binding!=="string"||!binding)throw new TypeError(`Missing asset binding for ${material.materialId}.`);if(crop)return `<div ${attrs} class="clip franken-clip ${roleClass}" data-crop-viewport="true" style="${style}overflow:hidden;width:420px;height:420px"><img src="${esc(binding)}" alt="" style="${cropMediaStyle(crop)}"></div>`;return `<img ${attrs} class="clip franken-clip ${roleClass}" src="${esc(binding)}" style="${style}">`;}if(material.kind==="video"){if(typeof binding!=="string"||!binding)throw new TypeError(`Missing asset binding for ${material.materialId}.`);return `<video ${attrs} class="clip franken-clip ${roleClass}" src="${esc(binding)}" data-media-start="0" muted playsinline style="${style}"></video>`;}if(material.kind==="text"){const parts=material.sourceIdentity.split(":");return `<div ${attrs} class="clip franken-clip franken-text ${roleClass}" style="${style}">${esc(parts.slice(2).join(":"))}</div>`;}return `<div ${attrs} class="clip franken-clip franken-topology ${roleClass}" data-layout-ignore style="${style}"></div>`;}
function compileHyperFramesFranken({plan,planHash,assetBindings={}}={}){
 if(!plan||typeof plan!=="object")throw new TypeError("HyperFrames projector requires a frozen Franken plan.");
 assertSupported(plan);assertPlanHash(plan,planHash);
 const materials=new Map(plan.materials.map(m=>[m.materialId,m]));let trackIndex=1;const nodes=[];const timeline=[];
 for(const scene of plan.scenes){for(const track of scene.tracks){for(const clip of track.clips){const material=materials.get(clip.materialId);if(!material)throw new TypeError(`Missing material ${clip.materialId}.`);const start=clip.startFrame/plan.fps,duration=clip.durationFrames/plan.fps,id=`hf-${clip.clipId}`;const attrs=`id="${esc(id)}" data-clip-id="${esc(clip.clipId)}" data-start="${start}" data-duration="${duration}" data-track-index="${trackIndex}" data-entrance="${esc(clip.entrance)}"`;const style=`left:${clip.transform.x*100}%;top:${clip.transform.y*100}%;translate:-50% -50%;scale:${clip.transform.scale};rotate:${clip.transform.rotationDegrees}deg;opacity:${clip.opacity};mix-blend-mode:${clip.blend};z-index:${trackIndex};`;nodes.push(materialNode(material,assetBindings[material.materialId],attrs,style,clip.crop,track.role));timeline.push({id,start,duration,entrance:clip.entrance,ease:["power3.out","back.out(1.4)","expo.out"][trackIndex%3]});trackIndex++;}}}
 const transitions=[];for(const t of plan.transitions){const boundary=plan.scenes.find(s=>s.sceneId===t.toSceneId)?.startFrame??0;const start=(boundary-t.durationFrames)/plan.fps,duration=t.durationFrames/plan.fps,id=`hf-transition-${t.transitionId}`;nodes.push(`<div id="${esc(id)}" class="clip franken-transition transition-${esc(t.kind)}" data-transition-id="${esc(t.transitionId)}" data-transition-kind="${esc(t.kind)}" data-start="${start}" data-duration="${duration}" data-track-index="${trackIndex}" data-layout-ignore></div>`);transitions.push({id,kind:t.kind,start,duration});trackIndex++;}
 const compositionId=`hf-franken-${planHash.slice(0,12)}`,seconds=plan.durationFrames/plan.fps;const timelineJson=JSON.stringify(timeline).replace(/</g,"\\u003c"),transitionJson=JSON.stringify(transitions).replace(/</g,"\\u003c");
 const html=`<!doctype html><html><head><meta charset="utf-8"><style>html,body{margin:0;background:#0B0B10;overflow:hidden}[data-composition-id="${compositionId}"]{position:relative;width:1280px;height:720px;overflow:hidden;background-color:#0B0B10;color:#F5F1E8}.franken-clip{position:absolute;transform-origin:center;max-width:70%;max-height:80%;box-sizing:border-box}.franken-clip img,.franken-clip video{display:block;max-width:720px;max-height:640px}.franken-text{font-family:sans-serif;font-size:68px;line-height:1.05;letter-spacing:-.03em;text-align:center;color:#F5F1E8;-webkit-text-stroke:2px #0B0B10;text-shadow:5px 5px 0 #D94B4B}.franken-topology{width:760px;height:760px;border:24px double #F5F1E8;border-radius:50%;box-shadow:0 0 0 14px #D94B4B inset}.franken-transition{position:absolute;inset:0;transform-origin:left center;background:#F4DF9C;z-index:999}.transition-panel-wipe{clip-path:inset(0)}.transition-radial-reveal{border-radius:50%;left:50%;top:50%;width:1400px;height:1400px;translate:-50% -50%;transform-origin:center;background:#F4DF9C}</style></head><body><div id="${compositionId}" data-composition-id="${compositionId}" data-start="0" data-duration="${seconds}" data-width="1280" data-height="720">${nodes.join("")}</div><script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script><script>window.__timelines=window.__timelines||{};const clips=${timelineJson};const transitions=${transitionJson};const tl=gsap.timeline({paused:true});for(const c of clips){tl.from('#'+c.id,{opacity:0,y:c.entrance==='arrive'?36:18,scale:0.92,duration:Math.min(.55,Math.max(.2,c.duration*.12)),ease:c.ease},c.start+.12);}for(const t of transitions){if(t.kind==='panel-wipe'){tl.from('#'+t.id,{scaleX:0,duration:t.duration,ease:'power4.inOut'},t.start);}else{tl.from('#'+t.id,{scale:0,duration:t.duration,ease:'expo.inOut'},t.start);}}window.__timelines['${compositionId}']=tl;</script></body></html>`;
 const trace=semanticTrace(plan);const manifest=deepFreeze(canonicalize({schema:"static-collective/franken-hyperframes-projection/v0",projectionId:compositionId,planHash,fps:plan.fps,durationFrames:plan.durationFrames,transitions:plan.transitions.map(t=>({transitionId:t.transitionId,kind:t.kind,durationFrames:t.durationFrames})),hiddenExitSemantics:false,trackCount:trackIndex-1,authority:"projection-only"}));
 return deepFreeze({manifest,html,designMarkdown:DESIGN_MD,semanticTrace:trace,projectionHash:hashCanonical({manifest,html},"HauntedToaster-FrankenHyperFrames-v0")});
}
module.exports={DESIGN_MD,compileHyperFramesFranken};
