"use strict";
const {canonicalize,deepFreeze,hashCanonical}=require("../../generation/canonical.cjs");
const {semanticTrace}=require("../trace.cjs");
const TRANSITIONS=new Set(["panel-wipe","radial-reveal","cut","hinge"]);
const BLENDS=new Set(["normal","screen"]);
function assertSupported(plan){for(const t of plan.transitions){if(!TRANSITIONS.has(t.kind))throw new TypeError(`Unsupported transition for Remotion: ${t.kind}.`);}const materials=new Map(plan.materials.map(m=>[m.materialId,m]));for(const scene of plan.scenes)for(const track of scene.tracks)for(const clip of track.clips){if(!BLENDS.has(clip.blend))throw new TypeError(`Unsupported blend for Remotion: ${clip.blend}.`);if(materials.get(clip.materialId)?.kind==="video"&&clip.crop)throw new TypeError("Remotion founding projector refuses video crop; shared renderer parity only admits image crop in v0.");for(const key of ["x","y","scale","rotationDegrees"]){if(!Number.isFinite(clip.transform?.[key]))throw new TypeError(`Unsupported transform for Remotion: ${key}.`);}}}
function assertPlanHash(plan,planHash){const clone=canonicalize(plan);if(clone.receipts)delete clone.receipts.planHash;const observed=hashCanonical(clone,"HauntedToaster-FrankenComposition-v0");if(observed!==planHash||plan.receipts?.planHash!==planHash)throw new TypeError("Remotion projection refuses a mutated or mismatched frozen plan.");}
function compileRemotionFranken({plan,planHash,assetBindings={}}={}){if(!plan||typeof plan!=="object")throw new TypeError("Remotion projector requires a frozen Franken plan.");assertSupported(plan);assertPlanHash(plan,planHash);const materials=plan.materials.map(m=>({materialId:m.materialId,kind:m.kind,sourceIdentity:m.sourceIdentity,digest:m.digest,binding:assetBindings[m.materialId]||null,...(m.derivation?{derivation:m.derivation}:{}),...(m.projectionTreatment?{projectionTreatment:m.projectionTreatment}:{})}));for(const m of materials){if((m.kind==="image"||m.kind==="video")&&!m.binding)throw new TypeError(`Missing asset binding for ${m.materialId}.`);}const bundle=deepFreeze(canonicalize({schema:"static-collective/franken-remotion-bundle/v0",authority:"projection-only",planHash,composition:{id:"Franken001",durationInFrames:plan.durationFrames,fps:plan.fps,width:1280,height:720},materials,scenes:plan.scenes,transitions:plan.transitions}));const trace=semanticTrace(plan);return deepFreeze({bundle,semanticTrace:trace,projectionHash:hashCanonical(bundle,"HauntedToaster-FrankenRemotion-v0")});}
module.exports={compileRemotionFranken};
